FROM php:8.2-fpm

# Install dependency
RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    unzip \ 
    libpng-dev \
    libonig-dev \
    libxml2-dev 

# install extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Inastall composer 
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www 

EXPOSE 8000

CMD ["php-fpm"]

